/**
 * Correlates frontend API calls with backend (Pino) logs.
 * Prefix `fe-` distinguishes IDs generated by this app from backend/proxy IDs.
 */
export function generateFrontendRequestId(): string {
  return `FE-${crypto.randomUUID()}`;
}
